### ISSUE TITLE
question about interoperation

### ISSUE THREAD

**Issue by publicocean0** [boostorg/fiber#160]
can i call a boost fiber from a JNI interface ?

**Comment by olk** [comment]
I don't know how JNI interacts with teh C++ runtime ...
I guess it should work but better you check it with a test app (would be nice if you would report your conclusion).

**Comment by publicocean0** [comment]
ok i m writing a little library for using fibers nativelly using java, because i was using another lib using another lib in c++ , in this way fiber is working in all the system.

How can i stop(interrupt) a fiber using c++ boost?
for example
`fiber.stop()`

How can i execute fiber join(time) using c+ boost(the default api dont accept a maximun time for waiting) ? 
for example:

` fiber.join(1000);`

**Comment by olk** [comment]
The boost.fiber-API is modelled after the std::thread-API, so you can use common patterns.
If you can want to stop a fiber you need to suspend it (for instance via boost::fibers::condition_variable) or let it return from the function you have passed to fiber's ctor (that terminates the fiber).
You can not serialized a fiber because this would not be require to copy the stack. At elast you would have to gauranttee the pointers to object (on stack or heap) etc. and additionally you could easily violate RAII ... so serializing would be a bad thing (ad is impossible without compielr support).
Fibers run in a thread; a thread can handle 1000x fibers. You need only threads if you want to run fibers in parallel.
